### ISSUE TITLE
package works great but how would one render a route with its parent layout route?

### ISSUE THREAD

**Issue by Jarrodsz** [jacobparis/remix-custom-routes#2]
It works great. 
Im still using this with v1 routes and also works fine "almost".

Before I used this file structure below ( which resulted in the app/routes/__auth.tsx, to be the parent layout for the login )
```
app/routes/__auth/login.tsx
app/routes/__auth.tsx
```

with your package I tried:

```
app/core/auth/routes/__auth.tsx
app/core/auth/routes/__auth/login.tsx
```

It renders the login route but without the parent layout, is there a way to have this package inherit the parent layout somehow?

Ofcourse your library is really new and i probably approach it the wrong way, but is there a neat way to resolve this? 

I plan to move to v2 routes perhaps I should just jump ship now. 

With v2 routes enables i guess it will be more easy something like 

```
/app/core/auth/routes/auth.tsx
/app/core/auth/routes/auth.login.tsx
```

**Comment by jacobparis** [comment]
> Im still using this with v1 routes and also works fine "almost"

At the moment I'm not looking at putting time into getting this to work with the v1 path format, though if someone were ambitious enough to implement that I would absolutely include it here. It'd take modification of the `getRouteIds` function to not strip out the parent folders. I think that would work without having to modify `getManifest` too.

> Is there a way I could let it work for /login also using the __auth.tsx parent route for the layout?

Yep, with the v2 style routes you use a single _ to make them pathless

```yml
app/
  anyFolder/
    _auth.route.tsx # layout file for your auth pages
    _auth.login.route.tsx
    _auth.logout.route.tsx
```
